// Copyright 2026 trevin-chow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDeploymentsPromoteCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "promote",
		Short: "Manage promote",
	}

	cmd.AddCommand(newDeploymentsPromoteDeploymentV1Cmd(flags))
	return cmd
}
