// Copyright 2026 trevin-chow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTeamCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "team",
		Short: "Publisher teams on the API network",
	}

	cmd.AddCommand(newTeamGetCmd(flags))
	cmd.AddCommand(newTeamGetWorkspacesCmd(flags))
	return cmd
}
