// Copyright 2026 matt-van-horn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
//
// PATCH(giacaglia): SaveLinearAPIKey, AuthHeader Bearer fallback for access_token, file AuthSource, ClearTokens clears api_key and OAuth fields.

package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/pelletier/go-toml/v2"
)

type Config struct {
	BaseURL       string    `toml:"base_url"`
	AuthHeaderVal string    `toml:"auth_header"`
	AuthSource    string    `toml:"-"`
	AccessToken   string    `toml:"access_token"`
	RefreshToken  string    `toml:"refresh_token"`
	TokenExpiry   time.Time `toml:"token_expiry"`
	ClientID      string    `toml:"client_id"`
	ClientSecret  string    `toml:"client_secret"`
	Path          string    `toml:"-"`
	LinearApiKey  string    `toml:"api_key"`
}

func Load(configPath string) (*Config, error) {
	cfg := &Config{
		BaseURL: "https://api.linear.app/graphql",
	}

	// Resolve config path
	path := configPath
	if path == "" {
		path = os.Getenv("LINEAR_CONFIG")
	}
	if path == "" {
		home, _ := os.UserHomeDir()
		path = filepath.Join(home, ".config", "linear-pp-cli", "config.toml")
	}
	cfg.Path = path

	// Try to load config file
	data, err := os.ReadFile(path)
	if err == nil {
		if err := toml.Unmarshal(data, cfg); err != nil {
			return nil, fmt.Errorf("parsing config %s: %w", path, err)
		}
	}

	// Env var overrides
	if v := os.Getenv("LINEAR_API_KEY"); v != "" {
		cfg.LinearApiKey = v
		cfg.AuthSource = "env:LINEAR_API_KEY"
	} else if cfg.LinearApiKey != "" {
		cfg.AuthSource = "config:api_key"
	} else if cfg.AccessToken != "" {
		cfg.AuthSource = "config:access_token"
	}

	// Base URL override (used by printing-press verify to point at mock/test servers)
	if v := os.Getenv("LINEAR_BASE_URL"); v != "" {
		cfg.BaseURL = v
	}

	return cfg, nil
}

func (c *Config) AuthHeader() string {
	if c.AuthHeaderVal != "" {
		return c.AuthHeaderVal
	}
	if c.LinearApiKey != "" {
		return c.LinearApiKey
	}
	if c.AccessToken != "" {
		return "Bearer " + c.AccessToken
	}
	return ""
}

func applyAuthFormat(format string, replacements map[string]string) string {
	if format == "" {
		return ""
	}
	for key, value := range replacements {
		format = strings.ReplaceAll(format, "{"+key+"}", value)
	}
	if strings.Contains(format, "{") {
		return ""
	}
	return format
}

func (c *Config) SaveTokens(clientID, clientSecret, accessToken, refreshToken string, expiry time.Time) error {
	c.ClientID = clientID
	c.ClientSecret = clientSecret
	c.AccessToken = accessToken
	c.RefreshToken = refreshToken
	c.TokenExpiry = expiry
	return c.save()
}

// SaveLinearAPIKey persists a Linear personal API key (GraphQL) under the api_key field.
// It clears OAuth token fields so AuthHeader resolves to the API key.
func (c *Config) SaveLinearAPIKey(key string) error {
	c.LinearApiKey = key
	c.AccessToken = ""
	c.RefreshToken = ""
	c.TokenExpiry = time.Time{}
	c.ClientID = ""
	c.ClientSecret = ""
	return c.save()
}

func (c *Config) ClearTokens() error {
	c.LinearApiKey = ""
	c.AccessToken = ""
	c.RefreshToken = ""
	c.TokenExpiry = time.Time{}
	c.ClientID = ""
	c.ClientSecret = ""
	c.AuthHeaderVal = ""
	return c.save()
}

func (c *Config) save() error {
	dir := filepath.Dir(c.Path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}
	data, err := toml.Marshal(c)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}
	return os.WriteFile(c.Path, data, 0o600)
}

// Ensure strings import is used
var _ = strings.ReplaceAll
