// Copyright 2026 gregvanhorn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPodcastsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "podcasts",
		Short: "Manage podcasts",
	}

	cmd.AddCommand(newPodcastsGetCmd(flags))
	cmd.AddCommand(newPodcastsSearchCmd(flags))
	cmd.AddCommand(newPodcastsEpisodesCmd(flags))
	return cmd
}
