// Copyright 2026 matt-van-horn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/mvanhorn/printing-press-library/library/project-management/linear/internal/cli"
	"github.com/mvanhorn/printing-press-library/library/project-management/linear/internal/client"
	"github.com/mvanhorn/printing-press-library/library/project-management/linear/internal/cliutil"
	"github.com/mvanhorn/printing-press-library/library/project-management/linear/internal/config"
	"github.com/mvanhorn/printing-press-library/library/project-management/linear/internal/mcp/cobratree"
	"github.com/mvanhorn/printing-press-library/library/project-management/linear/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("attachments_get",
			mcplib.WithDescription("Get a single attachment. Required: id. Returns the Attachment."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("audit-entry-types_get",
			mcplib.WithDescription("Fetch the catalog of audit log entry types Linear supports (e.g. user authentication, permission change, data export, setting modification). Returns each type's `type` slug and human-readable `description`. Use to enumerate the kinds of audited actions before filtering an `AuditEntry` query, not to fetch the audit entries themselves."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("auth-resolver-responses_get",
			mcplib.WithDescription("Get a single authresolverresponse. Returns the AuthResolverResponse."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("authentication-session-responses_get",
			mcplib.WithDescription("Get a single authenticationsessionresponse. Returns the AuthenticationSessionResponse."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("email-intake-addresses_get",
			mcplib.WithDescription("Get a single emailintakeaddress. Required: id. Returns the EmailIntakeAddress."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("favorites_get",
			mcplib.WithDescription("Get a single favorite. Required: id. Returns the Favorite."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("initiative-relations_get",
			mcplib.WithDescription("Get a single initiativerelation. Required: id. Returns the InitiativeRelation."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("initiative-to-projects_get",
			mcplib.WithDescription("Get a single initiativetoproject. Required: id. Returns the InitiativeToProject."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("initiatives_get",
			mcplib.WithDescription("Get a single initiative. Required: id. Returns the Initiative."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("integrations_create",
			mcplib.WithDescription("Create a Linear integration via the issueCreate-style mutation pipeline. Required: a `service` slug identifying the integration provider (e.g. `slack`, `github`) plus the OAuth/API config payload that service expects. Returns the new Integration's id, service, and connection state. Most users wire integrations through Linear's web UI; reach for this only when scripting workspace setup or migrating across orgs."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("integrations_delete",
			mcplib.WithDescription("Delete an existing Linear integration by id. Required: `id`. Optional: pass a flag to skip uninstalling the connection on the external service side (leave the third-party app installed even after Linear forgets it). Returns the removed Integration. Destructive — disables any automation or webhooks the integration was driving."),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/graphql", []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("issue-priority-values_get",
			mcplib.WithDescription("Get a single issuepriorityvalue. Returns the IssuePriorityValue."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("organizations_get",
			mcplib.WithDescription("Fetch the authenticated workspace (Linear `Organization`). No id needed — Linear scopes this to the workspace the API key belongs to. Returns workspace-level metadata: `id`, `name`, `urlKey`, plan/feature flags, member count, and policy settings. Use to detect plan tier, urlKey, or feature availability before calling features that are plan-gated."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("project-labels_get",
			mcplib.WithDescription("Get a single projectlabel. Required: id. Returns the ProjectLabel."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("project-milestones_get",
			mcplib.WithDescription("Get a single projectmilestone. Required: id. Returns the ProjectMilestone."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("project-relations_get",
			mcplib.WithDescription("Get a single projectrelation. Required: id. Returns the ProjectRelation."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("project-statuses_get",
			mcplib.WithDescription("Get a single projectstatus. Required: id. Returns the ProjectStatus."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("projects_get",
			mcplib.WithDescription("Get a single project. Required: id. Returns the Project."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("release-notes_get",
			mcplib.WithDescription("Get a single releasenote. Required: id. Returns the ReleaseNote."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("release-pipelines_get",
			mcplib.WithDescription("Fetch a single release pipeline by id. Required: `id` (the pipeline's UUID). Returns the pipeline's name, slug, color, owning team, and `approximateReleaseCount`. Use after `release-pipelines_list` (or a search) to load pipeline details before listing the releases inside it."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("release-stages_get",
			mcplib.WithDescription("Get a single releasestage. Required: id. Returns the ReleaseStage."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("releases_get",
			mcplib.WithDescription("Get a single release. Required: id. Returns the Release."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("roadmap-to-projects_get",
			mcplib.WithDescription("Get a single roadmaptoproject. Required: id. Returns the RoadmapToProject."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("roadmaps_get",
			mcplib.WithDescription("Get a single roadmap. Required: id. Returns the Roadmap."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("teams_get",
			mcplib.WithDescription("Fetch a single team by id. Required: `id` (team UUID — the team `key` like `ENG` does not work here; resolve key→UUID via `teams_list` or the local store first). Returns the Team object with id, key, name, color, owning organization, and references to the active cycle, default state, and feature flags. Use when you already have a UUID; for lookups by key or name, prefer `teams_list` with a filter."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("templates_get",
			mcplib.WithDescription("Fetch a single issue or document template by id. Required: `id`. Returns the template's name, type (issue / document / project), team scope, color, and the body / template data agents can apply when creating new entities. Use to render a template before substituting into an `issueCreate` or `documentCreate` mutation."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("user-settingses_get",
			mcplib.WithDescription("Fetch a UserSettings record by id (one settings row per user; UserSettings.id != User.id). Returns the user's notification preferences, calendar prefs, and `autoAssignToSelf` default. Use this when an agent needs to read a teammate's preferences before honoring them; for the authenticated user's own settings, the `viewer` query is the simpler path."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("users_get",
			mcplib.WithDescription("Fetch a single Linear workspace user by id. Required: `id` (user UUID — `me` is NOT accepted here; use the `viewer` query for the authenticated user). Returns the User object with name, displayName, email, active flag, admin flag, avatarUrl, and team memberships. Use after resolving an email or display name through `users_list`."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/graphql", []mcpParamBinding{}, []string{}),
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT only). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export LINEAR_API_KEY=<your-key>" +
					"\n      Run 'linear-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your API key." +
					"\n      Set it with: export LINEAR_API_KEY=<your-key>" +
					"\n      Run 'linear-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export LINEAR_API_KEY=<your-key>" +
					"\n      Run 'linear-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "linear-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "linear-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	// Block write operations
	upper := strings.ToUpper(strings.TrimSpace(query))
	for _, prefix := range []string{"INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE"} {
		if strings.HasPrefix(upper, prefix) {
			return mcplib.NewToolResultError("only SELECT queries are allowed"), nil
		}
	}

	db, err := store.OpenWithContext(ctx, dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "linear",
		"description": "Generated from GraphQL schema",
		"archetype":   "project-management",
		"tool_count":  28,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion linear-pp-cli binary.",
		"auth": map[string]any{
			"type": "api_key",
			"env_vars": []map[string]any{
				{
					"name":        "LINEAR_API_KEY",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "attachments",
				"description": "Manage attachments",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "audit-entry-types",
				"description": "Manage audit-entry-types",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "auth-resolver-responses",
				"description": "Manage auth-resolver-responses",
				"endpoints":   []string{"get"},
				"syncable":    true,
			},
			{
				"name":        "authentication-session-responses",
				"description": "Manage authentication-session-responses",
				"endpoints":   []string{"get"},
				"syncable":    true,
			},
			{
				"name":        "email-intake-addresses",
				"description": "Manage email-intake-addresses",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "favorites",
				"description": "Manage favorites",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "initiative-relations",
				"description": "Manage initiative-relations",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "initiative-to-projects",
				"description": "Manage initiative-to-projects",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "initiatives",
				"description": "Manage initiatives",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "integrations",
				"description": "Manage integrations",
				"endpoints":   []string{"create", "delete"},
			},
			{
				"name":        "issue-priority-values",
				"description": "Manage issue-priority-values",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "organizations",
				"description": "Manage organizations",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "project-labels",
				"description": "Manage project-labels",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "project-milestones",
				"description": "Manage project-milestones",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "project-relations",
				"description": "Manage project-relations",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "project-statuses",
				"description": "Manage project-statuses",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "projects",
				"description": "Manage projects",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "release-notes",
				"description": "Manage release-notes",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "release-pipelines",
				"description": "Manage release-pipelines",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "release-stages",
				"description": "Manage release-stages",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "releases",
				"description": "Manage releases",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "roadmap-to-projects",
				"description": "Manage roadmap-to-projects",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "roadmaps",
				"description": "Manage roadmaps",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "teams",
				"description": "Manage teams",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "templates",
				"description": "Manage templates",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "user-settingses",
				"description": "Manage user-settingses",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "users",
				"description": "Manage users",
				"endpoints":   []string{"get"},
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Today View", "command": "today", "description": "See all your issues for today across every team, ranked by priority and cycle deadline.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Bottleneck Detection", "command": "bottleneck", "description": "See which team members are overloaded and which issues are blocked before sprint planning.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Project Burndown", "command": "projects burndown", "description": "Project a project's landing date by linear-regressing remaining estimate against the team's measured velocity.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Cycle Comparison", "command": "cycles compare", "description": "Side-by-side metrics between any two cycles: completion %, scope added, scope cut, carryover, average cycle time.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Stale Issue Radar", "command": "stale", "description": "Find issues that haven't been touched in N days, grouped by team and project.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Slipped Issues", "command": "slipped", "description": "Show what carried over from last cycle into this cycle, grouped by team and reason heuristic.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Blocking Queue", "command": "blocking", "description": "Show issues you are blocking — sorted by impact (downstream count and priority).", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Duplicate Detection", "command": "similar", "description": "Find issues that look like duplicates of a query string using offline FTS5 fuzzy matching.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Velocity Trends", "command": "velocity", "description": "Track sprint completion rates over the last N cycles to spot productivity trends.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Initiatives Health", "command": "initiatives health", "description": "Rolled-up portfolio view per initiative: child project progress, milestone target-vs-projected dates, slippage flags.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Test Fixture Lifecycle", "command": "pp-test list", "description": "List Linear issues this CLI created in the current or named session, then archive them with pp-cleanup.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Trust Mode Mutation Guard", "command": "issues create", "description": "Refuse mutations on Linear issues not in the local pp_created ledger when --trust-mode strict is set; works on the...", "rationale": "", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Today View", "insight": ""},
			{"topic": "Bottleneck Detection", "insight": ""},
			{"topic": "Project Burndown", "insight": ""},
			{"topic": "Cycle Comparison", "insight": ""},
			{"topic": "Stale Issue Radar", "insight": ""},
			{"topic": "Slipped Issues", "insight": ""},
			{"topic": "Blocking Queue", "insight": ""},
			{"topic": "Duplicate Detection", "insight": ""},
			{"topic": "Velocity Trends", "insight": ""},
			{"topic": "Initiatives Health", "insight": ""},
			{"topic": "Test Fixture Lifecycle", "insight": ""},
			{"topic": "Trust Mode Mutation Guard", "insight": ""},
			{"topic": "Finding stale work", "insight": "Use the stale command or sql query to find items not updated recently. More reliable than scanning list results manually."},
			{"topic": "Load analysis", "insight": "When analyzing team workload, filter by assignee and status. Raw counts without status filtering are misleading."},
			{"topic": "Bulk operations", "insight": "For bulk status changes, prefer update endpoints over delete+create. Most PM APIs track history on updates."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
