// Copyright 2026 matt-van-horn. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
//
// PATCH(giacaglia): auth set-api-key persists api_key; auth set-token stores access_token; AuthHeader uses api_key or Bearer access_token.

package cli

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"github.com/mvanhorn/printing-press-library/library/project-management/linear/internal/config"
)

func newAuthCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "auth",
		Short: "Manage authentication (API keys and OAuth tokens)",
	}

	cmd.AddCommand(newAuthStatusCmd(flags))
	cmd.AddCommand(newAuthSetAPIKeyCmd(flags))
	cmd.AddCommand(newAuthSetTokenCmd(flags))
	cmd.AddCommand(newAuthLogoutCmd(flags))

	return cmd
}

func newAuthStatusCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "status",
		Short:   "Show authentication status",
		Example: "  linear-pp-cli auth status",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			w := cmd.OutOrStdout()
			header := cfg.AuthHeader()
			if header == "" {
				fmt.Fprintln(w, red("Not authenticated"))
				fmt.Fprintln(w, "")
				fmt.Fprintln(w, "Set your credentials:")
				fmt.Fprintln(w, "  export LINEAR_API_KEY=\"your-key-here\"")
				fmt.Fprintf(w, "  linear-pp-cli auth set-api-key <lin_api_...>\n")
				fmt.Fprintf(w, "  linear-pp-cli auth set-token <oauth_access_token>   # advanced\n")
				return authErr(fmt.Errorf("no credentials configured"))
			}

			fmt.Fprintln(w, green("Authenticated"))
			fmt.Fprintf(w, "  Source: %s\n", cfg.AuthSource)
			fmt.Fprintf(w, "  Config: %s\n", cfg.Path)
			return nil
		},
	}
}

func newAuthSetAPIKeyCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "set-api-key <key>",
		Short:   "Save a Linear personal API key to the config file",
		Example: "  linear-pp-cli auth set-api-key lin_api_abc123",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			if err := cfg.SaveLinearAPIKey(args[0]); err != nil {
				return configErr(fmt.Errorf("saving API key: %w", err))
			}

			fmt.Fprintf(cmd.OutOrStdout(), "API key saved to %s\n", cfg.Path)
			return nil
		},
	}
}

func newAuthSetTokenCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:   "set-token <token>",
		Short: "Save an OAuth access token to the config file (advanced)",
		Long: "Stores the value in access_token for OAuth-style token flows. " +
			"For Linear personal API keys (lin_api_…), use auth set-api-key or LINEAR_API_KEY.",
		Example: "  linear-pp-cli auth set-token <oauth_access_token>",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			if err := cfg.SaveTokens("", "", args[0], "", cfg.TokenExpiry); err != nil {
				return configErr(fmt.Errorf("saving token: %w", err))
			}

			fmt.Fprintf(cmd.OutOrStdout(), "Token saved to %s\n", cfg.Path)
			return nil
		},
	}
}

func newAuthLogoutCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "logout",
		Short:   "Clear stored credentials",
		Example: "  linear-pp-cli auth logout",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			if err := cfg.ClearTokens(); err != nil {
				return configErr(fmt.Errorf("clearing tokens: %w", err))
			}

			// Warn if env vars still set
			if os.Getenv("LINEAR_API_KEY") != "" {
				fmt.Fprintf(cmd.OutOrStdout(), "Config cleared. Note: LINEAR_API_KEY env var is still set.\n")
				return nil
			}
			fmt.Fprintln(cmd.OutOrStdout(), "Logged out. Credentials cleared.")
			return nil
		},
	}
}
