// Copyright 2026 trevin-chow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBookingsMarkAbsentCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "mark-absent",
		Short: "Manage mark absent",
	}

	cmd.AddCommand(newBookingsMarkAbsentBookingsMarkNoShowCmd(flags))
	return cmd
}
