// Copyright 2026 trevin-chow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBookingsRequestRescheduleCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "request-reschedule",
		Short: "Manage request reschedule",
	}

	cmd.AddCommand(newBookingsRequestRescheduleBookingsCmd(flags))
	return cmd
}
