// Copyright 2026 trevin-chow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newConferencingCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "conferencing",
		Short: "Manage conferencing",
	}

	cmd.AddCommand(newConferencingGetDefaultCmd(flags))
	cmd.AddCommand(newConferencingListInstalledAppsCmd(flags))
	cmd.AddCommand(newConferencingConnectCmd(flags))
	cmd.AddCommand(newConferencingDefaultCmd(flags))
	cmd.AddCommand(newConferencingDisconnectCmd(flags))
	cmd.AddCommand(newConferencingOauthCmd(flags))
	return cmd
}
